name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: YOUR_GITHUB_USERNAME
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
      - name: Push dist directory to output branch
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jaysolanki0906/jaysolanki0906.git
            git checkout output
            git add dist
            git commit -m "Update dist files"
            git push origin output --force
